export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_CONTACTS = 'SET_USER_CONTACTS';
export const SET_ALL_CONTACTS = 'SET_ALL_CONTACTS';
export const SET_LISTINGS = 'SET_LISTINGS';
export const SET_CUISINE_TYPES = 'SET_CUISINE_TYPES';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';